version: '3'

services:
  db_webinar:
    container_name: db_webinar
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - /opt/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin