"""Add table

Revision ID: 9c19b702acdd
Revises: 
Create Date: 2023-03-05 00:21:08.735769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c19b702acdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('course_name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('teacher',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('webinar_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('webinar',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('course', sa.Integer(), nullable=True),
                    sa.Column('teacher', sa.Integer(), nullable=True),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['course'], ['course.id'], ),
                    sa.ForeignKeyConstraint(['teacher'], ['teacher.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webinar')
    op.drop_table('teacher')
    op.drop_table('course')
    # ### end Alembic commands ###
